### ISSUE TITLE
Argument error with custom macro

### ISSUE THREAD

**Issue by smpallen99** [elixir-lang/gettext#176]
I created a custom sigil macro (see below) which has been working well on 0.13.1. Hower, in 0.15, I'm getting an argument error. I use this macro in 1000's of locations in several projects, so I'd really like to keep using it in newer versions of gettext.

My projects Gettext module:

```elixir
defmodule GollumXWeb.Gettext do
  use Gettext, otp_app: :gollum_x

  defmacro __using__(_ \\ []) do
    quote do
      import unquote(__MODULE__)
    end
  end

  defmacro sigil_g(text, _) do
    quote do
      gettext(unquote(text))
    end
  end
end
```

Usage:

```elixir
defmodule GollumX.MyMod do
  use GollumXWeb.Gettext

  def test do
    IO.puts ~g(Some localized text)
  end
end
```

The error: 

```
iex(3)> ~g(test)
** (ArgumentError) *gettext macros expect translation keys (msgid and msgid_plural) and
domains to expand to strings at compile-time, but the given msgid
doesn't.

Dynamic translations should be avoided as they limit gettext's
ability to extract translations from your source code. If you are
sure you need dynamic lookup, you can use the functions in the Gettext
module:

    string = "hello world"
    Gettext.gettext(GollumXWeb.Gettext, string)
   ...
```

After rolling back to 0.13.1, everything works fine.
 
```
iex(2)> ~g(test)
"test"
```

I suspect this is a parse/compile issue since the text should be bound at at compile time, not run time.

I'm using Elixir 1.6.2

**Comment by josevalim** [comment]
It will probably work if you change the macro to:

```elixir
  defmacro sigil_g({:<<>>, _, [text]}, _) do
    quote do
      gettext(unquote(text))
    end
  end
```

The reason is that `gettext` is expecting a literal string but the sigil receives them in the bit syntax. Extracting it out solves it.

Btw, this is a very nice use case of sigils.

We may want to fix this in gettext too but I am unsure. Since it is the first time we hear about it, I would wait for more scenarios.

**Comment by whatyouhide** [comment]
@josevalim Gettext used to cover this case IIRC because exactly of sigils, where the binary was wrapped in `:<<>>` even if it was a single binary with no interpolation. I remember you fixed this in Elixir at some point so I stopped handling this in Gettext itself. Unsure why the sigil is behaving this way :\

**Comment by josevalim** [comment]
We fixed our sigils but we may have other ones. So I think we need to do
that back?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by michalmuskala** [comment]
Wasn't it a reverse situation like calling `gettext(~S"foo")` instead of wrapping gettext in a sigil?

**Comment by josevalim** [comment]
Yes, exactly. We made sure that the sigil expanded to a string though,
which cause the ~g sigil implementation to break.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by whatyouhide** [comment]
Oh, the sigil still gets `{:<<>>, _, [text]}`, right. I think we should revert the behaviour and handle `{:<<>>, _, [text]}` then I guess. @josevalim would it make sense to have the sigil take the direct binary as well though, as another change to Elixir?

**Comment by josevalim** [comment]
>  @josevalim would it make sense to have the sigil take the direct binary as well though, as another change to Elixir?

No because it would be backwards incompatible. FWIW, we keep sigils like that because sigils may have interpolations and we want to clearly detect those.

**Comment by whatyouhide** [comment]
@josevalim oh yeah I know we do it for interpolation, I was wondering if we could expand the non-interpolation case so that `sigil_g` receives `"foo"` when called as `~g(foo)` instead of receiving `{:<<>>, _, ["foo"]}`. But I suspected it might be backwards incompat anyways. In any case, Gettext needs to be reverted here.

**Comment by smpallen99** [comment]
Just following up to say that @josevalim trick with the AST works like a charm. Thanks!!
